"""Generate per-embedding-size config YAMLs for the ae2d reconstruction ablation.

The 2D AutoencoderKL compresses each PET slice into a latent tensor before the
diffusion stages operate on it. The *embedding size* of that latent is the single
quantity we vary here: ``latent_channels`` (the channel depth of the latent map).

There is no CLI flag for ``latent_channels`` (it is read from the config by
``src.training.models.autoencoder2d.build_autoencoder_2d``), so every ablation
point needs its own config file. This script copies the base ``ae2d.yaml`` and
emits one variant per grid value, changing ONLY ``latent_channels`` and the
``output_dir`` (so runs do not clobber each other). Loss weights, perceptual
settings, augmentation and ``block_out_channels`` are kept identical so the latent
embedding size is the only varied factor.

Compression-ratio bookkeeping (for the report / intuition)
----------------------------------------------------------
The spatial downsampling factor is ``2 ** (len(block_out_channels) - 1)``. With
the default ``block_out_channels = [64, 128, 256]`` that is ``2**2 = 4``. So a
``128 x 128`` input slice produces a ``latent_channels x 32 x 32`` latent.

    input elements  = 128 * 128 * 1            = 16384
    latent elements = latent_channels * 32 * 32 = latent_channels * 1024
    compression     = 16384 / (latent_channels * 1024)

e.g. latent_channels=8 -> 2x compression; =4 -> 4x; =2 -> 8x; =16 -> 0.5x (an
expansion in element count, kept as the high-fidelity upper anchor of the sweep).

This script is torch-free / stdlib-only and runs on the Windows host or in WSL.
Prefer PyYAML if installed; otherwise fall back to a tiny templated writer that
reproduces the base file's simple structure.
"""

import os

# --- Ablation grid -----------------------------------------------------------
# Primary axis: latent embedding depth (channels). This is the "small" study --
# vary only the channel count, hold spatial compression fixed.
#
# A SECOND axis (spatial compression via len(block_out_channels)) can be added
# later by emitting variants with a distinct tag, e.g. a deeper/shallower
# block_out_channels list written as ae2d_lc{N}_d{LEVELS}.yaml. Keep the default
# to the channel sweep only so the report stays one-dimensional and readable.
# Single-point check (per user request): just verify encode->decode recon at the
# current embed size. Re-expand to e.g. [2, 4, 8, 16] to run the full sweep.
LATENT_CHANNELS_GRID = [8]

# Backbone for every ablation point. We override the base ae2d.yaml's
# block_out_channels so the sweep runs on a fixed, chosen capacity rather than the
# canonical config's value. [32, 64, 128] is a middle ground between the currently
# trained checkpoint ([16, 32, 64]) and the heavier ae2d.yaml default
# ([64, 128, 256]). It is still 3 levels, so the spatial downsampling stays /4 and
# the compression math below is unchanged -- only the per-level capacity differs.
BLOCK_OUT_CHANNELS = [32, 64, 128]

# Resolve repo-relative paths from this file's location so it works from any cwd.
_HERE = os.path.dirname(os.path.abspath(__file__))
_REPO = os.path.dirname(_HERE)
BASE_CONFIG = os.path.join(_REPO, "src", "training", "configs", "ae2d.yaml")
ABLATION_DIR = os.path.join(_REPO, "src", "training", "configs", "ablation")


def _load_base_yaml(path):
    """Load the base config. Returns (data_dict_or_None, raw_text).

    When PyYAML is available we round-trip through it (clean, robust). Otherwise
    we return None for the dict and fall back to text templating on the raw file.
    """
    with open(path, "r", encoding="utf-8") as fh:
        raw = fh.read()
    try:
        import yaml  # type: ignore
    except Exception:
        return None, raw
    return yaml.safe_load(raw), raw


def _write_with_yaml(data, latent_channels, out_path):
    """Emit a variant config via PyYAML (deep-copied + two keys overridden)."""
    import copy

    import yaml  # type: ignore

    cfg = copy.deepcopy(data)
    cfg["latent_channels"] = latent_channels
    cfg["output_dir"] = "outputs/ae2d_ablation/lc{}".format(latent_channels)
    model = cfg.get("model")
    if not isinstance(model, dict):
        model = {}
        cfg["model"] = model
    model["block_out_channels"] = list(BLOCK_OUT_CHANNELS)
    header = (
        "# AUTO-GENERATED by scripts/gen_ae2d_ablation_configs.py -- do not edit.\n"
        "# ae2d reconstruction ablation point: latent_channels={}.\n".format(latent_channels)
    )
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write(header)
        yaml.safe_dump(cfg, fh, default_flow_style=False, sort_keys=False)


def _write_with_template(raw, latent_channels, out_path):
    """Fallback: rewrite the two scalar lines in the raw base text in place.

    The base config keeps ``latent_channels`` and ``output_dir`` as simple
    top-level ``key: value`` scalars, so a line-oriented rewrite is safe and
    preserves all comments / ordering verbatim.
    """
    out_dir = "outputs/ae2d_ablation/lc{}".format(latent_channels)
    boc = "[{}]".format(", ".join(str(c) for c in BLOCK_OUT_CHANNELS))
    new_lines = []
    saw_lc = saw_out = False
    for line in raw.splitlines():
        if line.startswith("latent_channels:"):
            new_lines.append("latent_channels: {}".format(latent_channels))
            saw_lc = True
        elif line.startswith("output_dir:"):
            new_lines.append("output_dir: {}".format(out_dir))
            saw_out = True
        elif line.lstrip().startswith("block_out_channels:"):
            # Preserve the nested indentation (it lives under "model:").
            indent = line[: len(line) - len(line.lstrip())]
            new_lines.append("{}block_out_channels: {}".format(indent, boc))
        else:
            new_lines.append(line)
    # Append any key the base happened not to contain (defensive).
    if not saw_lc:
        new_lines.append("latent_channels: {}".format(latent_channels))
    if not saw_out:
        new_lines.append("output_dir: {}".format(out_dir))
    header = (
        "# AUTO-GENERATED by scripts/gen_ae2d_ablation_configs.py -- do not edit.\n"
        "# ae2d reconstruction ablation point: latent_channels={}.\n".format(latent_channels)
    )
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write(header)
        fh.write("\n".join(new_lines) + "\n")


def main():
    os.makedirs(ABLATION_DIR, exist_ok=True)
    data, raw = _load_base_yaml(BASE_CONFIG)

    for n in LATENT_CHANNELS_GRID:
        out_path = os.path.join(ABLATION_DIR, "ae2d_lc{}.yaml".format(n))
        if data is not None:
            _write_with_yaml(data, n, out_path)
        else:
            _write_with_template(raw, n, out_path)
        ratio = 16384.0 / (n * 1024.0)
        print(
            "wrote {}  (latent_channels={}, latent={}x32x32, compression={:.2f}x)".format(
                out_path, n, n, ratio
            )
        )


if __name__ == "__main__":
    main()
